#!/usr/bin/env python3
"""Validate evidence and assemble a dependency-free GitHub Pages artifact."""
import argparse
import hashlib
import json
import re
import shutil
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlparse

ROOT = Path(__file__).resolve().parents[1]


def validate():
    task_data = json.loads((ROOT / 'data/tasks.json').read_text())
    tasks = task_data['tasks']
    results = json.loads((ROOT / 'data/results.json').read_text())
    assert {t['id'] for t in tasks} == {'anticancer', 'cpp', 'd2', 'gsk3b', 'ood'}
    assert len(tasks) == 5
    expected_rounds = {'anticancer': 13, 'cpp': 7, 'd2': 9, 'gsk3b': 10, 'ood': 6}
    trace_count = 0
    for task in tasks:
        assert sum(s['rounds'] for s in task['stages']) == expected_rounds[task['id']]
        assert len({s['id'] for s in task['stages']}) == len(task['stages'])
        for stage in task['stages']:
            assert stage['summary'] and stage['title'] and stage['paperPages']
            assert all(1 <= page <= 43 for page in stage['paperPages'])
            for trace in stage['traces']:
                assert trace['label'] in {'POSITIVE', 'NEGATIVE', 'ABSTAIN'}
                assert trace['source'] and trace['rationale'] and trace['uncertainty']
                assert trace['paraphrased'] is True
                assert re.fullmatch(r'[a-f0-9]{64}', trace['sourceSha256'])
                trace_count += 1
    provenance = json.loads((ROOT / 'data/provenance.json').read_text())
    assert hashlib.sha256((ROOT / provenance['paper']['file']).read_bytes()).hexdigest() == provenance['paper']['sha256']
    assert len(results) == 4
    for result in results:
        assert len(result['metrics']) == 3
        assert sum(row['method'] == 'LFD' for row in result['rows']) == 1
        assert all(len(row['values']) == 3 for row in result['rows'])
    serialized = json.dumps(task_data)
    assert 'sourceFiles' not in serialized
    assert not re.search(r'/iopsstor/|/capstor/|/users/|(?:github_pat_|ghp_)[A-Za-z0-9_]{10,}', serialized)
    for file in (ROOT / 'data').glob('*.json'):
        assert not re.search(r'/iopsstor/|/capstor/|/users/', file.read_text()), file
    class Links(HTMLParser):
        def handle_starttag(self, tag, attrs):
            for name, value in attrs:
                if name in {'src', 'href'} and value:
                    url = urlparse(value)
                    if not url.scheme and not url.netloc and url.path:
                        assert (ROOT / unquote(url.path)).is_file(), value
    # site-data.js is generated next; validate the other static assets now.
    html = (ROOT / 'index.html').read_text().replace(' src="data/site-data.js"', '')
    Links().feed(html)
    return task_data, results, trace_count


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--output-dir', type=Path, default=ROOT / 'dist')
    args = parser.parse_args()
    task_data, results, count = validate()
    payload = {'tasks': task_data['tasks'], 'results': results}
    script = '// Generated by scripts/build.py from the public JSON sources.\nwindow.LFD_DATA = ' + json.dumps(payload, ensure_ascii=False, separators=(',', ':')).replace('</', '<\\/') + ';\n'
    (ROOT / 'data/site-data.js').write_text(script)
    dist = args.output_dir.resolve()
    dist.mkdir(exist_ok=True)
    for name in ['index.html', 'site.css', 'site.js', '.nojekyll']:
        shutil.copy2(ROOT / name, dist / name)
    for name in ['assets', 'data']:
        shutil.copytree(ROOT / name, dist / name, dirs_exist_ok=True)
    print(f'Validated 5 tasks, 23 stages, {count} trace examples, 4 result tables and the paper hash.')
    print(f'Site artifact: {dist}')


if __name__ == '__main__':
    main()
